# Generated by Django 5.1.4 on 2025-01-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
