# Generated by Django 5.1.4 on 2025-01-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
